<?php

namespace App\Http\Controllers\Test;

use App\Http\Controllers\Controller;
use App\Models\Account\Group;
use App\Models\Account\GroupPermission;
use App\Models\Account\Permission;
use App\Models\Account\Role;
use App\Models\Account\RolePermission;
use App\Models\Account\User;
use App\Models\Account\UserPermission;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class TestController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //
    }

    public function AddTestDummy(Request $r)
    {
        $Array = collect([
            [
                "group" => [
                    "name" => "Super Admin",
                    "permission" => [
                        "Setting.GroupManagement",
                        "Setting.UserManagement",
                        "Setting.UserProfile",
                        "SIAP.Disposition",
                        "SIAP.OutgoingLetter",
                        "SIAP.RequestData",
                    ],
                ],
                "role" => [
                    "name" => "Super Admin",
                    "permission" => [
                        "Setting.GroupManagement",
                        "Setting.GroupManagement.ViewSearch",
                        "Setting.GroupManagement.ViewDetail",
                        "Setting.GroupManagement.Add",
                        "Setting.GroupManagement.Edit",

                        "Setting.UserManagement",
                        "Setting.UserManagement.Member.ViewSearch",
                        "Setting.UserManagement.Member.ViewDetail",
                        "Setting.UserManagement.Member.Add",
                        "Setting.UserManagement.Member.Edit",
                        "Setting.UserManagement.Role.ViewSearch",
                        "Setting.UserManagement.Role.ViewDetail",
                        "Setting.UserManagement.Role.Add",
                        "Setting.UserManagement.Role.Edit",

                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",

                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.Level.A",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.Level.C",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.Comment",

                        "SIAP.Disposition.Send",
                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                        "SIAP.RequestData.Level.A",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.B",
                        "SIAP.RequestData.Level.C",
                        "SIAP.RequestData.Level.D",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
                "user" => [
                    "name" => "Super Admin",
                    "email" => "admin@mail.com",
                    "permission" => [
                        "Setting.GroupManagement",
                        "Setting.GroupManagement.ViewSearch",
                        "Setting.GroupManagement.ViewDetail",
                        "Setting.GroupManagement.Add",
                        "Setting.GroupManagement.Edit",

                        "Setting.UserManagement",
                        "Setting.UserManagement.Member.ViewSearch",
                        "Setting.UserManagement.Member.ViewDetail",
                        "Setting.UserManagement.Member.Add",
                        "Setting.UserManagement.Member.Edit",
                        "Setting.UserManagement.Role.ViewSearch",
                        "Setting.UserManagement.Role.ViewDetail",
                        "Setting.UserManagement.Role.Add",
                        "Setting.UserManagement.Role.Edit",

                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",

                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.Send",

                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                    ],
                ],
            ], [
                "group" => [
                    "name" => "Pengurus",
                    "permission" => [
                        "Setting.UserProfile",
                        "SIAP.Disposition",
                        "SIAP.OutgoingLetter",
                        "SIAP.RequestData",
                    ],
                ],
                "role" => [
                    "name" => "Ketua 1",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.Level.A",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.Level.C",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.Comment",

                        "SIAP.Disposition.Send",
                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                        "SIAP.RequestData.Level.A",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.B",
                        "SIAP.RequestData.Level.C",
                        "SIAP.RequestData.Level.D",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
                "user" => [
                    "name" => "Herman Soepardjono",
                    "email" => "herman.soepardjono@mail.com",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.Level.A",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Comment",

                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.A",
                        "SIAP.RequestData.Level.A2",
                    ],
                ],
            ], [
                "group" => [
                    "name" => "Pengurus",
                    "permission" => null,
                ],
                "role" => [
                    "name" => "Ketua 2",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",

                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.Level.A",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.Level.C",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.Comment",
                        "SIAP.Disposition.Send",

                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                        "SIAP.RequestData.Level.A",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.B",
                        "SIAP.RequestData.Level.C",
                        "SIAP.RequestData.Level.D",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
                "user" => [
                    "name" => "Juani",
                    "email" => "juani@mail.com",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",

                        "SIAP.Disposition",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Comment",

                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.B",
                    ],
                ],
            ], [
                "group" => [
                    "name" => "Pengurus",
                    "permission" => null,
                ],
                "role" => [
                    "name" => "Ketua 3",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.Level.A",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.Level.C",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.Comment",

                        "SIAP.Disposition.Send",
                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                        "SIAP.RequestData.Level.A",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.B",
                        "SIAP.RequestData.Level.C",
                        "SIAP.RequestData.Level.D",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
                "user" => [
                    "name" => "Muh Hariyanto",
                    "email" => "muh.hariyanto@mail.com",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Comment",

                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.B",
                    ],
                ],
            ], [
                "group" => [
                    "name" => "Pengurus",
                    "permission" => null,
                ],
                "role" => [
                    "name" => "Sekretaris",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.Level.A",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.Level.C",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.Comment",

                        "SIAP.Disposition.Send",
                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                        "SIAP.RequestData.Level.A",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.B",
                        "SIAP.RequestData.Level.C",
                        "SIAP.RequestData.Level.D",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
                "user" => [
                    "name" => "M Syaiful Faqih",
                    "email" => "syaiful.faqih@mail.com",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Comment",

                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.B",
                    ],
                ],
            ], [
                "group" => [
                    "name" => "Pengurus",
                    "permission" => null,
                ],
                "role" => [
                    "name" => "Bendahara",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.Level.A",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.Level.C",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.Comment",

                        "SIAP.Disposition.Send",
                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                        "SIAP.RequestData.Level.A",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.B",
                        "SIAP.RequestData.Level.C",
                        "SIAP.RequestData.Level.D",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
                "user" => [
                    "name" => "S. Julistiyah",
                    "email" => "julistiyah@mail.com",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Comment",

                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.B",
                    ],
                ],
            ], [
                "group" => [
                    "name" => "Pusat",
                    "permission" => [
                        "Setting.UserProfile",
                        "SIAP.Disposition",
                        "SIAP.OutgoingLetter",
                        "SIAP.RequestData",
                    ],
                ],
                "role" => [
                    "name" => "Sekretaris Eksekutif (SE)",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.Comment",

                        "SIAP.Disposition.Send",
                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                        "SIAP.RequestData.Level.A",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.B",
                        "SIAP.RequestData.Level.C",
                        "SIAP.RequestData.Level.D",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
                "user" => [
                    "name" => "Staff SE",
                    "email" => "staff.se@mail.com",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Send",
                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",
                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                    ],
                ],
            ], [
                "group" => [
                    "name" => "Pusat",
                    "permission" => null,
                ],
                "role" => [
                    "name" => "Manajer Umum",
                    "permission" => [
                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.Level.A",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.Level.C",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.Comment",

                        "SIAP.Disposition.Send",
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",
                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                        "SIAP.RequestData.Level.A",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.B",
                        "SIAP.RequestData.Level.C",
                        "SIAP.RequestData.Level.D",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
                "user" => [
                    "name" => "Eva Marliyanti",
                    "email" => "marliyanti@mail.com",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.Level.C",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Comment",

                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.C",
                    ],
                ],
            ], [
                "group" => [
                    "name" => "Pusat",
                    "permission" => null,
                ],
                "role" => [
                    "name" => "Kabag HRD",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.Level.A",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.Level.C",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.Comment",

                        "SIAP.Disposition.Send",
                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                        "SIAP.RequestData.Level.A",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.B",
                        "SIAP.RequestData.Level.C",
                        "SIAP.RequestData.Level.D",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
                "user" => [
                    "name" => "Mannaria Harahap",
                    "email" => "mannaria@mail.com",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.Comment",

                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.D",
                    ],
                ],
            ], [
                "group" => [
                    "name" => "Pusat",
                    "permission" => null,
                ],
                "role" => [
                    "name" => "Kabag Finance",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.Level.A",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.Level.C",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.Comment",

                        "SIAP.Disposition.Send",
                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                        "SIAP.RequestData.Level.A",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.B",
                        "SIAP.RequestData.Level.C",
                        "SIAP.RequestData.Level.D",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
                "user" => [
                    "name" => "Kartini",
                    "email" => "kartini@mail.com",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.Comment",

                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.D",
                    ],
                ],
            ], [
                "group" => [
                    "name" => "Divisi Inti",
                    "permission" => [
                        "Setting.UserProfile",
                        "SIAP.Disposition",
                        "SIAP.OutgoingLetter",
                        "SIAP.RequestData",
                    ],
                ],
                "role" => [
                    "name" => "Manajer Divisi Inti",
                    "permission" => [
                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.Level.A",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.Level.C",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.Comment",

                        "SIAP.Disposition.Send",
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                        "SIAP.RequestData.Level.A",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.B",
                        "SIAP.RequestData.Level.C",
                        "SIAP.RequestData.Level.D",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
                "user" => [
                    "name" => "Samsul Hadi Santoso",
                    "email" => "samsul@mail.com",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Comment",

                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.D",
                    ],
                ],
            ], [
                "group" => [
                    "name" => "Divisi Inti",
                    "permission" => null,
                ],
                "role" => [
                    "name" => "Kabag Support",
                    "permission" => [
                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.Level.A",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.Level.C",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.Comment",

                        "SIAP.Disposition.Send",
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                        "SIAP.RequestData.Level.A",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.B",
                        "SIAP.RequestData.Level.C",
                        "SIAP.RequestData.Level.D",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
                "user" => [
                    "name" => "Dwi Prasetyowati",
                    "email" => "prasetyowati@mail.com",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Comment",

                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
            ], [
                "group" => [
                    "name" => "Divisi Inti",
                    "permission" => null,
                ],
                "role" => [
                    "name" => "Kabag Kualitas",
                    "permission" => [
                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.Level.A",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.Level.C",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.Comment",

                        "SIAP.Disposition.Send",
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                        "SIAP.RequestData.Level.A",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.B",
                        "SIAP.RequestData.Level.C",
                        "SIAP.RequestData.Level.D",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
                "user" => [
                    "name" => "Siska Norma Prasasti",
                    "email" => "siska.prasasti@mail.com",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Comment",

                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
            ], [
                "group" => [
                    "name" => "Divisi Perdagangan & Jasa",
                    "permission" => [
                        "Setting.UserProfile",
                        "SIAP.Disposition",
                        "SIAP.OutgoingLetter",
                        "SIAP.RequestData",
                    ],
                ],
                "role" => [
                    "name" => "Manajer Divisi Perdagangan & Jasa",
                    "permission" => [
                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.Level.A",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.Level.C",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.Comment",

                        "SIAP.Disposition.Send",
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                        "SIAP.RequestData.Level.A",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.B",
                        "SIAP.RequestData.Level.C",
                        "SIAP.RequestData.Level.D",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
                "user" => [
                    "name" => "Latifah",
                    "email" => "latifah@mail.com",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Comment",

                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.D",
                    ],
                ],
            ], [
                "group" => [
                    "name" => "Divisi Perdagangan & Jasa",
                    "permission" => null,
                ],
                "role" => [
                    "name" => "SPV Angkutan",
                    "permission" => [
                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.Level.A",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.Level.C",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.Comment",

                        "SIAP.Disposition.Send",
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                        "SIAP.RequestData.Level.A",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.B",
                        "SIAP.RequestData.Level.C",
                        "SIAP.RequestData.Level.D",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
                "user" => [
                    "name" => "Khoirul Anwar",
                    "email" => "khoirul.anwar@mail.com",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Comment",

                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
            ], [
                "group" => [
                    "name" => "Divisi Perdagangan & Jasa",
                    "permission" => null,
                ],
                "role" => [
                    "name" => "Kabag DC",
                    "permission" => [
                        "SIAP.Disposition",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Add",
                        "SIAP.Disposition.Edit",
                        "SIAP.Disposition.Level.Z",
                        "SIAP.Disposition.Level.A",
                        "SIAP.Disposition.Level.B",
                        "SIAP.Disposition.Level.C",
                        "SIAP.Disposition.Level.D",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.Comment",

                        "SIAP.Disposition.Send",
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.OutgoingLetter.Approver",

                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.Z",
                        "SIAP.RequestData.Level.A",
                        "SIAP.RequestData.Level.A2",
                        "SIAP.RequestData.Level.B",
                        "SIAP.RequestData.Level.C",
                        "SIAP.RequestData.Level.D",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
                "user" => [
                    "name" => "Muhammad Ghozali",
                    "email" => "muhammad.ghozali@mail.com",
                    "permission" => [
                        "Setting.UserProfile",
                        "Setting.UserProfile.View",
                        "Setting.UserProfile.Edit",
                        "Setting.UserProfile.ChangePassword",
                        "SIAP.Disposition",
                        "SIAP.Disposition.Level.E",
                        "SIAP.Disposition.ViewSearch",
                        "SIAP.Disposition.ViewDetail",
                        "SIAP.Disposition.Comment",

                        "SIAP.OutgoingLetter",
                        "SIAP.OutgoingLetter.ViewSearch",
                        "SIAP.OutgoingLetter.ViewDetail",
                        "SIAP.OutgoingLetter.Add",
                        "SIAP.OutgoingLetter.Edit",
                        "SIAP.RequestData",
                        "SIAP.RequestData.ViewSearch",
                        "SIAP.RequestData.ViewDetail",
                        "SIAP.RequestData.Level.E",
                    ],
                ],
            ],
        ])->values();

        foreach ($Array->toArray() as $k => $v) {
            $G = Group::updateOrcreate([
                'name' => $v['group']['name'],
                'is_active' => 1,
            ]);
            if (!is_null($v['group']['permission'])) {
                $Ps = Permission::where(['is_active' => 1])
                    ->whereIn('name', $v['group']['permission'])
                    ->get()
                    ->map(function ($i) use ($G) {
                        return [
                            'group_id' => $G->id,
                            'permission_id' => $i['id'],
                            'is_active' => 1,
                            'created_at' => Carbon::now(),
                            'updated_at' => Carbon::now(),
                        ];
                    });
                GroupPermission::insert($Ps->toArray() ?? []);
            }

            $R = Role::updateOrcreate([
                'name' => $v['role']['name'],
                'is_active' => 1,
            ]);
            if (!is_null($v['role']['permission'])) {
                $Ps = Permission::where(['is_active' => 1])
                    ->whereIn('name', $v['role']['permission'])
                    ->get()
                    ->map(function ($i) use ($G, $R) {
                        return [
                            'group_id' => $G->id,
                            'role_id' => $R->id,
                            'permission_id' => $i['id'],
                            'is_active' => 1,
                            'created_at' => Carbon::now(),
                            'updated_at' => Carbon::now(),
                        ];
                    });
                RolePermission::insert($Ps->toArray() ?? []);
            }

            $U = User::updateOrcreate([
                'name' => $v['user']['name'],
                'email' => $v['user']['email'],
                'password' => Hash::make("Rahasia123&", [
                    'rounds' => 10,
                ]),
                'status' => 1,
            ]);
            if (!is_null($v['user']['permission'])) {
                $Ps = Permission::where(['is_active' => 1])
                    ->whereIn('name', $v['user']['permission'])
                    ->get()
                    ->map(function ($i) use ($G, $R, $U) {
                        return [
                            'user_id' => $U->id,
                            'role_id' => $R->id,
                            'group_id' => $G->id,
                            'permission_id' => $i['id'],
                            'is_active' => 1,
                            'created_at' => Carbon::now(),
                            'updated_at' => Carbon::now(),
                        ];
                    });
                UserPermission::insert($Ps->toArray() ?? []);
            }
        }
        return response([
            "api_version" => "1.0",
            "message" => "success add test user dummy",
        ], 201);
    }
}
